### ISSUE TITLE
Delete IMCE::OWL2-SysML Integration::IMCE.owl2-mof2::customization

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/profileGenerator#1]
The IMCE::owl2-mof2 DSL Customization was developed when the IMCE project was heavily involved in using MD for authoring model-to-model transformations where it was necessary to have access from the MD UI to the metaclass of a given element, regardless of any other DSL customization applied.

In the MagicDraw community, it is often the case that someone wants to use a DSL embedded in UML but hide UML leaving the appearance that MagicDraw supports the DSL as a native modeling tool. MagicDraw's DSL Customization facility enables this by allowing a particular DSL customization
to hide metaproperties from the UML impelementation underneath. While achieving the objective of hiding UML underneath, it has the negative consequence of making it difficult to find out what is the actual UML element underneath a particular DSL customized rendering of that element.

Years ago, the IMCE project used to include in the JPL distribution of MagicDraw an IMCE plugin that included the implementation of binary expressions to support efficient DSL customization.
Although the IMCE plugin is long gone, there is a leftover reference to a binary expression that came from this plugin in `IMCE::OWL2-SysML Integration::IMCE.owl2-mof2::customization::Metaclass`.

In fact, none of the DSL customizations in IMCE::OWL2-SysML Integration::IMCE.owl2-mof2::customization` are relevant anymore; this customization package should be deleted.

**Comment by dwagmuse** [comment]
Delete away.
As long as you are in there, can you add a few words in the README explaining how to build?
Probably also need some details about how to run it, but leave out specific details about any JPL resources if this is going to open source. Do we have a separate repo (scripts?) where we can keep specific configured scripts to build the IMCE profile?
